{% set name = "flytekitplugins-pandera" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-pandera-{{ version }}.tar.gz
  sha256: 12b2390722021aa6e7151fbbe737a951eea45f30b013f36b3de40bb861dc63be

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - flytekit >=1.0.0b3,<1.2.0
    - pandera >=0.7.1

test:
  imports:
    - flytekitplugins.pandera
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flytekitplugins-pandera/
  summary: Pandera plugin for flytekit
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Pandera plugin for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-pandera/](https://pypi.org/project/flytekitplugins-pandera/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-pandera

extra:
  recipe-maintainers:
    - sugatoray
